In [16]:
from sklearn.cluster import KMeans
import numpy as np
from sklearn.manifold import TSNE

X = np.load('data/data_lstm/x_feature_arima.npy')
print(X.shape)
X[0]

kmeans = KMeans(n_clusters=1, random_state=0).fit(X)
kmeans.labels_
kmeans.cluster_centers_

points = []

for i in range(410):
    a_point = kmeans.predict(X[i])
#     a_point = array.reshape(a_point,(1,-1))
    points.append(a_point)
    

    
points.shape
# X_embedded = TSNE(n_components =2).fit_transform(points)
# array([1, 1, 1, 0, 0, 0], dtype=int32)
# >>> kmeans.predict([[0, 0], [12, 3]])
# array([1, 0], dtype=int32)
# >>> kmeans.cluster_centers_
# array([[10.,  2.],
#        [ 1.,  2.]])

(410, 81)


ValueError: Expected 2D array, got 1D array instead:
array=[ 1.16078649e+02 -1.18220053e+02  4.01968796e-01  5.34049414e+00
  4.94193359e+01  4.53321940e+01  4.89494901e+01 -3.49466455e+00
 -2.11015651e+00  1.29726956e+02  1.39299516e+02  6.46775561e+01
  1.20861394e+00  5.05850001e+00  5.37999264e+00  1.51465031e+01
  3.64810318e+01  2.98716055e+00  1.91252367e+00  1.97782774e+01
  4.14535633e+02 -1.27459400e+01  5.65101894e+00  1.14062215e+01
  7.97265625e+01  8.19824219e+01  8.98185200e+01  3.58129410e-02
  6.36381469e-01  1.32476800e+02  1.34641216e-01 -1.98629800e+02
 -4.10937593e+00 -3.82138481e-01  2.89453125e+01  1.41601562e+01
  1.18182400e+01 -8.09955037e+00 -6.81839926e+00 -1.50000000e+01
  7.00303964e-01  4.92924441e-01  5.19621682e-02  2.84762751e-02
  5.10421014e-01  5.26104706e-01  1.36226160e-01  3.96518827e-02
  4.42039995e-02  4.92582972e-01  7.84641068e-01  6.07679466e-01
  2.52086811e-01  2.37009448e+00  2.37009448e+00  2.00161918e-02
  9.85160736e-01  1.30968994e-02  5.45803940e-03  6.34275711e-01
  7.11028951e-01  1.03830334e-01  7.39576899e-03  7.78237107e-03
  9.86813378e-01  1.16861436e-02  3.18864775e-01  6.01001669e-02
  4.84140234e-02  5.17529215e-02  1.06844741e-01  6.01001669e-02
  2.67111853e-02  2.33722871e-02  1.50250417e-02 -1.29552455e-01
 -2.17991739e-02  1.42092681e-02  3.75710652e-01  1.42092681e-02
  3.75710652e-01].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.