In [47]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
#from sklearn import manifold, datasets
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

In [48]:
X = np.load("data_lstm/x_feature_arima.npy")
y = np.load("data_lstm/y_raw.npy")
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [49]:
def remove_wrong_points(X, y):
    X_zeros = []
    for i in range(len(y)):
        if y[i] == 0:
            X_zeros.append(np.append(X[i], i))
    X_zeros = np.array(X_zeros)
    #X_zeros[:,:-1]
    Kmean = KMeans(n_clusters=1).fit(X_zeros[:,:-1])
    center = Kmean.cluster_centers_
    center.reshape(81)
    distance = []
    for zeros in X_zeros:
        dist = np.linalg.norm(zeros[:-1] - center)
        distance.append((dist,zeros[-1]))
    distance = sorted(distance, key=lambda a_entry: a_entry[0]) 
    wrong_points = distance[int(0.8*len(distance)):]
    wrong_points = np.array(wrong_points)
    wrong_points = wrong_points.transpose()
    new_X = np.delete(X, wrong_points[1],0)
    new_y = np.delete(y, wrong_points[1],0)
    np.save("y_new.npy", new_y)
    np.save("x_new.npy", new_X)
    return new_X, new_y
remove_wrong_points(X, y)


/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future


(array([[-5.01534074e+00, -1.52327897e+02, -5.03349022e-01, ...,
          4.47639555e-01, -6.93889390e-18,  4.47639555e-01],
        [ 3.41561386e+01, -1.26827257e+02,  4.03903482e-01, ...,
          4.57323339e-01,  2.52564346e-02,  4.57323339e-01],
        [-3.76614708e+00, -1.57271764e+02, -1.37330008e+00, ...,
          5.26541588e-01,  2.36567605e-02,  5.26541588e-01],
        ...,
        [ 1.08485301e+02, -1.42857416e+02,  1.49059489e-01, ...,
          4.92664178e-01, -3.02481038e-03,  4.92664178e-01],
        [ 6.10580413e+01, -1.67874071e+02, -1.59396701e-01, ...,
          2.92742555e-01, -1.67998050e-09,  2.92742555e-01],
        [ 1.04320211e+02, -3.09454582e+02,  8.17094902e-01, ...,
          4.70007525e-01, -6.21668142e-08,  4.70007525e-01]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 

In [52]:
#import matplotlib.pyplot as plt
#plt.plot([i[0] for i in distance[int(0.85*len(distance))]],"rx")